#!/bin/bash
# QDNet installation script

################################################################################
#                         BEGIN DEPENDENCY CHECK                               #
################################################################################

missing_dependencies=0
dhcp_client=0
echo Checking for dependencies...

// list all dependencies (NOT INCLUDING DHCP CLIENTS)
for dep in bc zenity
do

	type $dep &> /dev/null
	if [ $? -eq 1 ]
	then
		echo $dep is missing, please install it.
		missing_dependencies=1
	fi
done

if [ $missing_dependencies -eq 1 ]
then
	exit 1
fi

// list all dhcp clients that you want to search for.
for client in dhclient dhcpcd
do
	type $client &> /dev/null
	if [ $? -eq 0 ]
	then
		cat ../qdnet_etc/qdnet.conf | sed -e "s/^DHCP_CLIENT=\([[:alpha:]]*\)/DHCP_CLIENT=$client/" >> ../qdnet_etc/qdnet.tmp
		mv ../qdnet_etc/qdnet.tmp ../qdnet_etc/qdnet.conf
		dhcp_client=1;
	fi
done

if [ $dhcp_client -eq 1 ]
then
	echo No DHCP client found. Please install one.
	exit 1
fi
################################################################################
#                         END DEPENDENCY CHECK                                 #
################################################################################


################################################################################
#                         START INSTALLATION                                   #
################################################################################
echo Installing qdnet...

echo Creating qdnet group
groupadd qdnet &> /dev/null

echo Creating configuration files
mkdir -p /etc/qdnet
cp -r ./qdnet_etc/* /etc/qdnet/
chown root:qdnet -R /etc/qdnet/
chmod 644 -R /etc/qdnet/
chmod 600 /etc/qdnet/qdnet.pwd

echo Copying icon set
mkdir -p /usr/share/qdnet
cp -r ./share/qdnet/* /usr/share/qdnet/

echo Installing binaries
mkdir -p /tmp/qdnet
cp -r ./bin/* /tmp/qdnet/
chown root:qdnet -R /tmp/qdnet/*
chmod 500 /tmp/qdnet/*
chmod 550 /tmp/qdnet/qdteller
chmod 550 /tmp/qdnet/qdnetc
cp -r /tmp/qdnet/* /usr/bin/
rm -r /tmp/qdnet

# note to self: may need gzip man pages instead of bz2
echo Installing man pages
cp -r ./man/*.bz2 /usr/share/man/man8/

echo Creating devices
mkfifo /dev/qdnet &> /dev/null
chown root:qdnet /dev/qdnet
chmod 420 /dev/qdnet

cat <<HEREDOC
  ___  ____  _   _      _   
 / _ \|  _ \| \ | | ___| |_ 
| | | | | | |  \| |/ _ \ __|
| |_| | |_| | |\  |  __/ |_ 
 \__\_\____/|_| \_|\___|\__|
 by Panther Linux User Group 

Installation completed!
======================
If you would like a regular user to be able to use qdnet
just add that user to the qdnet group:

gpasswd -a [user] qdnet // must use root privileges

 
Have fun!

HEREDOC
