#!/bin/bash
# assumes that calling script has already brought interface up. 
# This script sets all configuration. DHCPCD needs to run after 
# script for connect to network.
# must have three parameters passed. 
# $1=interface | $2=network essid | $3=encryption type

# ensure that only root can run this program
. qdcheck

# source the configuration for the program
source /etc/qdnet/qdnet.conf

# returns error code 70 to mean that configuration was unsucessful.
E_ERR_CONFIG=70
config_wpa() {
	# get password for network
	pass=`cat "$PASSWD_LOC/qdnet.pwd" | grep "$essid" | awk -F"\t" '{print $2}'`
	# insert necessary information into wpa_supplicant.conf
	wpa_passphrase "$essid" "$pass" > "/etc/qdnet/wpa_supplicant.conf"
	# point interface to network
	iwconfig $interface essid "$essid"
	# load interface with pass key 
	wpa_supplicant -B -Dwext -i $interface -c "/etc/qdnet/wpa_supplicant.conf"
}

config_wep() {
	# get password for network
	key=`cat "$PASSWD_LOC/qdnet.pwd" | grep "$essid" | awk -F"\t" '{print $2}'`
	# load interface with hex key. If key provided not in hex format notify user with custom error message.
	iwconfig wlan0 essid "$essid" key "$key" 2>/dev/null || echo "Security configuration unsuccessful. Encryption key must be in hexadecimal." && exit $E_ERR_CONFIG
}

# store scripts parameters into variables for use inside functions
interface="$1"
essid="$2"

case "$3" in
	"WEP") config_wep;;
	"Unknown") config_wep;;
	"WPA") config_wpa;;
	*) echo "Security configuration unsuccessful.  Unsupported encryption type."
esac
